Add OpenAIChatClient: use LangChain for auto retry
RomanEngeler1805/LegalResearchAssistant pull request #32
Opened 2023-06-22 21:24 UTC by jwayne

I added a class `OpenAIChatClient` in `src/client/openai_chat.py`. This class has 2 methods:
* `generate(prompt)`: generates a single chat completion via a single call to OpenAI
* `multi_generate(prompts)`: generates multiple chat completions via parallel calls to OpenAI.

All generations via this class have automatic retries built in via LangChain. See [LangChain's `OpenAIChat` class](https://github.com/hwchase17/langchain/blob/9d42621fa4385e519f702b7005d475781033188c/langchain/llms/openai.py#L659) for available params (all of which can be passed directly into `OpenAIChatClient` during initialization.

You can test this new class by running `python client/openai_chat.py`.

Finally, I replaced all references to the predecessor `ChatOpenAI`. This affected `1_Results.py` and `reasoner.py`.

2023-06-23 13:29 UTC, RomanEngeler1805 commented on src/openai_chat.py
hey josh, any particular reason why you have kept the original script?

2023-06-23 14:15 UTC, RomanEngeler1805 requested changes
Hey Josh, 
nice work on this is the new client for the chat completion endpoint!

- the unittests fail (test_reasoner.py due to the new chat client)
- it would be great to also have a new client for the completion endpoint, as I'm using it to pre-filter the search results. I'll add a notion task board ticket for it

2023-06-23 14:15 UTC, RomanEngeler1805 commented on scripts/pages/1_📚_Results.py
> +# https://stackoverflow.com/a/27437149/1232944
though I still get quite frequently:

  _File "/Users/romanengeler/hackathons/venv-notion/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 565, in _run_script
    exec(code, module.__dict__)
  File "/Users/romanengeler/hackathons/LegalResearchAssistant/scripts/pages/1_📚_Results.py", line 18, in <module>
    stop_words_german = stopwords.words("german")
  File "/Users/romanengeler/hackathons/venv-notion/lib/python3.10/site-packages/nltk/corpus/util.py", line 121, in __getattr__
    self.__load()
  File "/Users/romanengeler/hackathons/venv-notion/lib/python3.10/site-packages/nltk/corpus/util.py", line 95, in __load
    args, kwargs = self.__args, self.__kwargs
AttributeError: 'WordListCorpusReader' object has no attribute '_LazyCorpusLoader__args'_

2023-06-23 22:41 UTC, jwayne commented on src/openai_chat.py
Accident, I'll remove.

2023-06-23 22:41 UTC, jwayne commented on src/reasoner.py
>          return answer_summary[0], concise_answer_docs[0], references
Good catch. Typically, comments are preferred. The flow we'd use at Opal is:
- engineer submits PR
- reviewer leaves comments
- engineer fixes and merges PR

2023-06-23 22:41 UTC, jwayne commented on scripts/pages/1_📚_Results.py
> +# https://stackoverflow.com/a/27437149/1232944
Ugh, that's a pain. Having `ranker` be initialized in the global context fixed this for me. Not sure why it's still happening for you. I'm not able to replicate it unfortunately..

Any ideas on unusual setup from your side that might be causing this? E.g. you're starting from a fresh env where this isn't already downloaded, you're on a slow connection, etc

2023-06-26 12:32 UTC, RomanEngeler1805 commented on scripts/pages/1_📚_Results.py
> +# https://stackoverflow.com/a/27437149/1232944
let's leave it for now and observe in the the live (streamlit) env. if it persists there, we can still think about a fix

2023-06-26 12:35 UTC, RomanEngeler1805 approved these changes

2023-06-26 15:29 UTC, RomanEngeler1805 commented
Hey Josh,
1) I have pushed a new class llm_filter in in src.ranker on Thursday. This class uses the openai api as well. do you want to refactor the class now, or should we close the current PR and then add a new PR for it? (note that this class has unittests as well)
2) the test_reasoner.py unittest fail (python -m unittest test_reasoner.py)

2023-06-26 22:56 UTC, merged